### ISSUE TITLE
Add to ESPHome docs

### ISSUE THREAD

**Issue by glmnet** [mikosoft83/pithy_screen_menu_system#1]
Hey there. Did you add this to https://esphome.io/guides/diy.html

If not please send a PR. This looks very nice. 

Thanks.

**Comment by mikosoft83** [comment]
Thanks for the comment. I'll have a look.
I'm currently working on a HTML/Javacsript config generator to make it easier to create the whole menu tree. Also I have some more ideas to implement so this'll be updated in some time.

**Comment by mikosoft83** [comment]
It's added now
